### Get all notes
GET http://localhost:3000/api/notes
Accept: application/json
### Add a new note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "title": "Ako si onesimus",
  "body": "Ayieieiei"
}

### Delete a note
DELETE http://localhost:3000/api/notes
Content-Type: application/json

{
  "id": "1753026533272"
}


### Get Color
GET http://localhost:3000/api/color
Content-Type: application/json


### New Color
POST http://localhost:3000/api/color
Content-Type: application/json

{
  "hex": "#002b36"
}